<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Unit;

/**
 * Seeder for populating the units (OPD and sub‑units) for
 * Pemerintah Kota Banjarmasin.  The data below is derived
 * from the research summarised in the conversation.  Each
 * unit includes its code, name, acronym, type (OPD or SUB),
 * parent_code (null for top‑level OPD), and a brief
 * description of its function.  Tags and other optional
 * fields are initialised as empty arrays or sensible
 * defaults.
 */
class UnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Daftar lengkap unit Organisasi Perangkat Daerah (OPD) Kota Banjarmasin serta beberapa contoh sub‑unit.
        // Setiap entri mencakup kode unit, induk (null untuk OPD), root_code, tipe, nama, singkatan, level, status root,
        // urutan, deskripsi dan tag.  Tag disimpan sebagai JSON untuk kompatibilitas dengan cast array.
        $units = [
            [
                'code'        => '1.02.0.00.0.00.01',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.01',
                'type'        => 'OPD',
                'name'        => 'Sekretariat Daerah Kota Banjarmasin',
                'acronym'     => 'SETDA',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 1,
                'description' => 'Dukungan administrasi dan koordinasi bagi Walikota, termasuk perumusan kebijakan dan pembinaan kecamatan.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.02',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.02',
                'type'        => 'OPD',
                'name'        => 'Sekretariat DPRD Kota Banjarmasin',
                'acronym'     => 'SETWAN',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 2,
                'description' => 'Memberikan dukungan administratif dan fasilitasi kepada DPRD dalam melaksanakan tugas legislatif.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.03',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.03',
                'type'        => 'OPD',
                'name'        => 'Inspektorat Kota Banjarmasin',
                'acronym'     => 'INSPEKTORAT',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 3,
                'description' => 'Melaksanakan pengawasan internal, audit, dan penjaminan mutu pada seluruh perangkat daerah.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.04',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.04',
                'type'        => 'OPD',
                'name'        => 'Badan Perencanaan Pembangunan Penelitian dan Pengembangan Daerah Kota Banjarmasin',
                'acronym'     => 'BAPPEDALITBANG',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 4,
                'description' => 'Menyusun perencanaan pembangunan daerah, melakukan penelitian dan pengembangan, serta mengkoordinasikan perencanaan antar‑OPD.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.05',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.05',
                'type'        => 'OPD',
                'name'        => 'Badan Kepegawaian Daerah, Pendidikan dan Pelatihan Kota Banjarmasin',
                'acronym'     => 'BKD DIKLAT',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 5,
                'description' => 'Mengelola manajemen pegawai daerah serta pengembangan kompetensi dan pelatihan.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.06',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.06',
                'type'        => 'OPD',
                'name'        => 'Badan Pengelolaan Keuangan, Pendapatan dan Aset Daerah Kota Banjarmasin',
                'acronym'     => 'BPKPAD',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 6,
                'description' => 'Mengelola perencanaan, pelaksanaan, dan pertanggungjawaban keuangan daerah serta pendapatan dan aset.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.07',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.07',
                'type'        => 'OPD',
                'name'        => 'Dinas Kesehatan Kota Banjarmasin',
                'acronym'     => 'DINKES',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 7,
                'description' => 'Menyelenggarakan urusan pemerintahan bidang kesehatan, termasuk perencanaan program kesehatan, pencegahan penyakit, dan pembinaan fasilitas kesehatan.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.08',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.08',
                'type'        => 'OPD',
                'name'        => 'Dinas Pendidikan Kota Banjarmasin',
                'acronym'     => 'DISDIK',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 8,
                'description' => 'Mengelola pendidikan dasar dan menengah, peningkatan mutu guru, serta fasilitasi satuan pendidikan.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.09',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.09',
                'type'        => 'OPD',
                'name'        => 'Dinas Pekerjaan Umum dan Penataan Ruang Kota Banjarmasin',
                'acronym'     => 'DPUPR',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 9,
                'description' => 'Mengurus pembangunan infrastruktur, pemeliharaan jalan, jembatan, dan pengaturan tata ruang kota.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.10',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.10',
                'type'        => 'OPD',
                'name'        => 'Dinas Perhubungan Kota Banjarmasin',
                'acronym'     => 'DISHUB',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 10,
                'description' => 'Mengatur transportasi dan lalu‑lintas di wilayah kota termasuk terminal, perparkiran, dan angkutan sungai.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.11',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.11',
                'type'        => 'OPD',
                'name'        => 'Dinas Sosial Kota Banjarmasin',
                'acronym'     => 'DINSOS',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 11,
                'description' => 'Menangani kesejahteraan sosial, pemberian bantuan, dan perlindungan sosial masyarakat.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.12',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.12',
                'type'        => 'OPD',
                'name'        => 'Dinas Lingkungan Hidup Kota Banjarmasin',
                'acronym'     => 'DLH',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 12,
                'description' => 'Memfokuskan pengelolaan lingkungan hidup, pengendalian pencemaran, dan pengelolaan sampah.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.13',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.13',
                'type'        => 'OPD',
                'name'        => 'Dinas Kebudayaan, Kepemudaan, Olahraga dan Pariwisata Kota Banjarmasin',
                'acronym'     => 'DISBUDPORAPAR',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 13,
                'description' => 'Mengembangkan kebudayaan, kepemudaan, olahraga, serta destinasi pariwisata di kota.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.14',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.14',
                'type'        => 'OPD',
                'name'        => 'Dinas Kependudukan dan Pencatatan Sipil Kota Banjarmasin',
                'acronym'     => 'DISDUKCAPIL',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 14,
                'description' => 'Mengelola administrasi kependudukan (KTP, KK) serta pencatatan sipil seperti kelahiran dan perkawinan.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.15',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.15',
                'type'        => 'OPD',
                'name'        => 'Dinas Komunikasi, Informatika, Statistik Kota Banjarmasin',
                'acronym'     => 'DISKOMINFOTIK',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 15,
                'description' => 'Menangani penyebarluasan informasi, pengelolaan sistem informasi pemerintahan, statistik sektoral, dan persandian.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.16',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.16',
                'type'        => 'OPD',
                'name'        => 'Dinas Ketahanan Pangan, Pertanian dan Perikanan Kota Banjarmasin',
                'acronym'     => 'DKP3',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 16,
                'description' => 'Menjamin ketahanan pangan, pengembangan pertanian perkotaan, dan perikanan sungai.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.17',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.17',
                'type'        => 'OPD',
                'name'        => 'Dinas Perdagangan dan Perindustrian Kota Banjarmasin',
                'acronym'     => 'DISPERDAGIN',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 17,
                'description' => 'Mengatur sektor perdagangan dan perindustrian, pengelolaan pasar, serta pembinaan industri kecil.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.18',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.18',
                'type'        => 'OPD',
                'name'        => 'Dinas Perumahan Rakyat dan Kawasan Permukiman Kota Banjarmasin',
                'acronym'     => 'DPRKP',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 18,
                'description' => 'Menangani urusan perumahan rakyat, penataan kawasan permukiman, fasilitasi pertanahan, dan rusunawa.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.19',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.19',
                'type'        => 'OPD',
                'name'        => 'Dinas Koperasi, Usaha Mikro, Perindustrian dan Tenaga Kerja Kota Banjarmasin',
                'acronym'     => 'DINKOPNAKER',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 19,
                'description' => 'Membina koperasi, usaha mikro, industri rumah tangga, serta mediasi dan perlindungan tenaga kerja.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.20',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.20',
                'type'        => 'OPD',
                'name'        => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu Kota Banjarmasin',
                'acronym'     => 'DPMPTSP',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 20,
                'description' => 'Melayani perizinan usaha dan penanaman modal secara terpadu dan mempromosikan investasi.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.21',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.21',
                'type'        => 'OPD',
                'name'        => 'Dinas Pemberdayaan Perempuan dan Perlindungan Anak Kota Banjarmasin',
                'acronym'     => 'DPPPA',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 21,
                'description' => 'Mendorong kesetaraan gender, pemberdayaan perempuan, dan perlindungan hak anak.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.22',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.22',
                'type'        => 'OPD',
                'name'        => 'Dinas Pengendalian Penduduk, Keluarga Berencana, dan Pemberdayaan Masyarakat Kota Banjarmasin',
                'acronym'     => 'DPPKBPM',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 22,
                'description' => 'Membina dan memperkuat kapasitas masyarakat serta lembaga kelurahan untuk pembangunan.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.23',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.23',
                'type'        => 'OPD',
                'name'        => 'Badan Kesatuan Bangsa dan Politik Kota Banjarmasin',
                'acronym'     => 'KESBANGPOL',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 23,
                'description' => 'Membangun wawasan kebangsaan dan menjaga stabilitas politik serta membina ormas dan partai politik.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.24',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.24',
                'type'        => 'OPD',
                'name'        => 'Badan Penanggulangan Bencana Daerah Kota Banjarmasin',
                'acronym'     => 'BPBD',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 24,
                'description' => 'Melakukan mitigasi, kesiapsiagaan, respons, dan pemulihan bencana di tingkat kota.',
                'tags'        => json_encode(['opd']),
            ],
            [
                'code'        => '1.02.0.00.0.00.25',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.25',
                'type'        => 'OPD',
                'name'        => 'Satuan Polisi Pamong Praja Kota Banjarmasin',
                'acronym'     => 'SATPOLPP',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 25,
                'description' => 'Menegakkan peraturan daerah, menjaga ketertiban umum, dan memberikan layanan pemadam kebakaran.',
                'tags'        => json_encode(['opd']),
            ],
	    [
                'code'        => '1.02.0.00.0.00.26',
                'parent_code' => null,
                'root_code'   => '1.02.0.00.0.00.26',
                'type'        => 'OPD',
                'name'        => 'Dinas Pemadam Kebakaran dan Penyelamatan Kota Banjarmasin',
                'acronym'     => 'DPKP',
                'level'       => 1,
                'is_root'     => true,
                'sequence'    => 25,
                'description' => 'memberikan layanan pemadam kebakaran dan penyelamatan.',
                'tags'        => json_encode(['opd']),
            ],
            // Sub‑unit examples
            [
                'code'        => '1.02.0.00.0.00.05.01',
                'parent_code' => '1.02.0.00.0.00.05',
                'root_code'   => '1.02.0.00.0.00.05',
                'type'        => 'SUB',
                'name'        => 'Bidang Mutasi dan Promosi',
                'acronym'     => 'MUTASI',
                'level'       => 2,
                'is_root'     => false,
                'sequence'    => 1,
                'description' => 'Mengelola mutasi dan promosi pegawai.',
                'tags'        => json_encode(['sub-unit']),
            ],
            [
                'code'        => '1.02.0.00.0.00.05.02',
                'parent_code' => '1.02.0.00.0.00.05',
                'root_code'   => '1.02.0.00.0.00.05',
                'type'        => 'SUB',
                'name'        => 'Bidang Pendidikan dan Pelatihan',
                'acronym'     => 'DIKLAT',
                'level'       => 2,
                'is_root'     => false,
                'sequence'    => 2,
                'description' => 'Mengelola pendidikan dan pelatihan pegawai.',
                'tags'        => json_encode(['sub-unit']),
            ],

            [
                'code'        => '1.02.0.00.0.00.07.01',
                'parent_code' => '1.02.0.00.0.00.07',
                'root_code'   => '1.02.0.00.0.00.07',
                'type'        => 'SUB',
                'name'        => 'Unit Pelaksana Teknis Puskesmas',
                'acronym'     => 'UPT PUSKESMAS',
                'level'       => 2,
                'is_root'     => false,
                'sequence'    => 1,
                'description' => 'Unit teknis kesehatan yang memberikan pelayanan langsung kepada masyarakat di bawah Dinas Kesehatan.',
                'tags'        => json_encode(['sub-unit']),
            ],
	    [
                'code'        => '1.02.0.00.0.00.18.01',
                'parent_code' => '1.02.0.00.0.00.18',
                'root_code'   => '1.02.0.00.0.00.18',
                'type'        => 'SUB',
                'name'        => 'Unit Pelaksana Teknis Rusunawa',
                'acronym'     => 'UPT RUSUNAWA',
                'level'       => 2,
                'is_root'     => false,
                'sequence'    => 1,
                'description' => 'Unit teknis yang memberikan pelayanan rumah susun sederhana sewa di bawah Dinas Perkim',
                'tags'        => json_encode(['sub-unit']),
            ],	
        ];

        // Simpan setiap entri unit menggunakan model Unit. updateOrCreate menjaga idempotensi ketika seeder dijalankan ulang.
        foreach ($units as $data) {
            Unit::updateOrCreate(
                ['code' => $data['code']],
                $data
            );
        }
    }
}